# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c034da80f2134917ceacec7383a0e5641a7515ebb73186717f98bb77d523c66dc3831102c92363e8d95bf25a247083c69412ccf08f23d5b115e6a38f648c4303

test:
  secret_key_base: bee1c44f10fc80bfe44ef0a7c848018dfa278b6dbb7bcc33d6eacf3d9f5d5c9a487d9b491c407ab5937102f9ab46f87ecb039d8a90904a77f4518e668ad4546f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
